# Generated by Django 3.1.4 on 2021-01-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
    ]
