# Generated by Django 3.1.4 on 2021-01-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixx', '0002_pixxx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixxx',
            name='image',
            field=models.ImageField(blank=True, upload_to='pixx/static/img/'),
        ),
    ]
