# Generated by Django 3.1.4 on 2021-01-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixx', '0003_auto_20210102_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixxx',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
