# Generated by Django 2.2.12 on 2021-01-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixx', '0005_contactformmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
